spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engine
    username: engine
    password: engine
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true